services:
  - type: web
    name: projeto-iphone
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT frontend.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: projeto-iphone-db
          property: connectionString
  - type: pgsql
    name: projeto-iphone-db
    databaseName: projeto_iphone
    user: projeto_iphone_user